module.exports = [
  { name: `Green Apple`, main_type: `Produce`, sub_type: `Fruit` },
  { name: `Banana`, main_type: `Produce`, sub_type: `Fruit` },
  { name: `Orange`, main_type: `Produce`, sub_type: `Fruit` },
  { name: `Strawberries`, main_type: `Produce`, sub_type: `Fruit` },
  { name: `Blueberries`, main_type: `Produce`, sub_type: `Fruit` },
  { name: `Green Grapes, Seedless`, main_type: `Produce`, sub_type: `Fruit` },
  { name: `Pineapple`, main_type: `Produce`, sub_type: `Fruit` },
  { name: `Mango`, main_type: `Produce`, sub_type: `Fruit` },
  { name: `Watermelon`, main_type: `Produce`, sub_type: `Fruit` },
  { name: `Cantaloupe`, main_type: `Produce`, sub_type: `Fruit` },
  { name: `Carrots`, main_type: `Produce`, sub_type: `Vegetable` },
  { name: `Broccoli`, main_type: `Produce`, sub_type: `Vegetable` },
  { name: `Cauliflower`, main_type: `Produce`, sub_type: `Vegetable` },
  { name: `Cucumber, Seedless`, main_type: `Produce`, sub_type: `Vegetable` },
  { name: `Spinach`, main_type: `Produce`, sub_type: `Vegetable` },
  { name: `Red Bell Pepper`, main_type: `Produce`, sub_type: `Vegetable` },
  { name: `Tomato, Vine`, main_type: `Produce`, sub_type: `Vegetable` },
  { name: `Zucchini`, main_type: `Produce`, sub_type: `Vegetable` },
  { name: `Onion, Spanish`, main_type: `Produce`, sub_type: `Vegetable` },
  { name: `Potato, Russet`, main_type: `Produce`, sub_type: `Vegetable` },
  { name: `Salmon, Farm-Raised`, main_type: `Meat`, sub_type: `Seafood` },
  { name: `Tuna, Bluefin`, main_type: `Meat`, sub_type: `Seafood` },
  {
    name: `Shrimp, Farm-Raised, Frozen`,
    main_type: `Meat`,
    sub_type: `Seafood`,
  },
  { name: `Scallop, U-10, Fresh`, main_type: `Meat`, sub_type: `Seafood` },
  { name: `Lobster, Live`, main_type: `Meat`, sub_type: `Seafood` },
  { name: `Chicken Breast`, main_type: `Meat`, sub_type: `Poultry` },
  { name: `Ground Turkey`, main_type: `Meat`, sub_type: `Poultry` },
  { name: `Duck Breast`, main_type: `Meat`, sub_type: `Poultry` },
  { name: `Cornish Game Hen`, main_type: `Meat`, sub_type: `Poultry` },
  { name: `Turkey Breast`, main_type: `Meat`, sub_type: `Poultry` },
  { name: `Pork Chop`, main_type: `Meat`, sub_type: `Pork` },
  { name: `Pork Tenderloin`, main_type: `Meat`, sub_type: `Pork` },
  { name: `Ground Pork`, main_type: `Meat`, sub_type: `Pork` },
  { name: `Baby Back Ribs`, main_type: `Meat`, sub_type: `Pork` },
  { name: `Bacon, Hickory`, main_type: `Meat`, sub_type: `Pork` },
  { name: `Ground Beef, 80/20`, main_type: `Meat`, sub_type: `Beef` },
  { name: `Steak, Sirloin`, main_type: `Meat`, sub_type: `Beef` },
  { name: `Steak, Ribeye`, main_type: `Meat`, sub_type: `Beef` },
  { name: `Beef Brisket`, main_type: `Meat`, sub_type: `Beef` },
  { name: `Beef Short Ribs`, main_type: `Meat`, sub_type: `Beef` },
  {
    name: `Organic Valley Milk, Organic, Whole`,
    main_type: `Dairy & Eggs`,
    sub_type: `Milk`,
  },
  {
    name: `Land O Lakes Butter, Unsalted`,
    main_type: `Dairy & Eggs`,
    sub_type: `Butter`,
  },
  { name: `Cheese, Manchego`, main_type: `Dairy & Eggs`, sub_type: `Cheese` },
  {
    name: `Wallaby Organic No Sugar Added Greek Yogurt`,
    main_type: `Dairy & Eggs`,
    sub_type: `Yogurt`,
  },
  {
    name: `Daisy Pure & Natural Sour Cream`,
    main_type: `Dairy & Eggs`,
    sub_type: `Other`,
  },
  { name: `Large Eggs`, main_type: `Dairy & Eggs`, sub_type: `Eggs` },
  {
    name: `Large Eggs, Free-Range`,
    main_type: `Dairy & Eggs`,
    sub_type: `Eggs`,
  },
  {
    name: `Quail Eggs, Free-Range`,
    main_type: `Dairy & Eggs`,
    sub_type: `Eggs`,
  },
  {
    name: `Liquid Death Mountain Water, 16.9 oz Cans`,
    main_type: `Beverages`,
    sub_type: `Water`,
  },
  {
    name: `VOSS Premium Still Bottled Water - 500ml`,
    main_type: `Beverages`,
    sub_type: `Water`,
  },
  {
    name: `Coca-Cola Cola, Original Taste`,
    main_type: `Beverages`,
    sub_type: `Soda`,
  },
  { name: `Simply Juice, Lemonade`, main_type: `Beverages`, sub_type: `Juice` },
  { name: `Lipton Black Tea`, main_type: `Beverages`, sub_type: `Tea` },
  {
    name: `Starbucks Coffee, 100% Arabica, Ground, Medium Roast, Breakfast Blend`,
    main_type: `Beverages`,
    sub_type: `Coffee`,
  },
  {
    name: `Red Bull Energy Drink, Sugar Free, 12 oz`,
    main_type: `Beverages`,
    sub_type: `Other`,
  },
  {
    name: `Gatorade Thirst Quencher, Lemon-Lime, 20 oz`,
    main_type: `Beverages`,
    sub_type: `Other`,
  },
  {
    name: `Vita Coco Coconut Water, The Original, 16.9 oz`,
    main_type: `Beverages`,
    sub_type: `Other`,
  },
  {
    name: `AriZona Iced Tea & Lemonade, Half and Half, Lite`,
    main_type: `Beverages`,
    sub_type: `Tea`,
  },
  {
    name: `Swiss Miss Hot Cocoa Mix, Marshmallow`,
    main_type: `Beverages`,
    sub_type: `Other`,
  },
  {
    name: `Health-Ade Kombucha, Pink Lady Apple`,
    main_type: `Beverages`,
    sub_type: `Other`,
  },
  {
    name: `Saratoga Spring Water, Carbonated`,
    main_type: `Beverages`,
    sub_type: `Water`,
  },
  {
    name: `Bragg Apple Cider Vinegar, Organic`,
    main_type: `Dried Goods`,
    sub_type: `Other`,
  },
  {
    name: `RiceSelect Jasmati, White`,
    main_type: `Dried Goods`,
    sub_type: `Grains`,
  },
  {
    name: `De Cecco Spaghetti, No. 12, Slow Dried`,
    main_type: `Dried Goods`,
    sub_type: `Pasta`,
  },
  {
    name: `RiceSelect Tri-Color Quinoa 22 oz. Jar`,
    main_type: `Dried Goods`,
    sub_type: `Grains`,
  },
  { name: `Goya Lentils`, main_type: `Dried Goods`, sub_type: `Grains` },
  {
    name: `Goya Low Sodium Chick Peas`,
    main_type: `Dried Goods`,
    sub_type: `Canned Goods`,
  },
  {
    name: `Goya Premium Black Beans`,
    main_type: `Dried Goods`,
    sub_type: `Canned Goods`,
  },
  {
    name: `Near East Roasted Garlic & Olive Oil Couscous Mix`,
    main_type: `Dried Goods`,
    sub_type: `Other`,
  },
  {
    name: `Quaker Oats, 100% Whole Grain, Quick 1-Minute`,
    main_type: `Dried Goods`,
    sub_type: `Grains`,
  },
  {
    name: `Bear Naked Granola Cereal, Breakfast Snacks, Vanilla Almond`,
    main_type: `Dried Goods`,
    sub_type: `Other`,
  },
  {
    name: `P.A.N. Corn Meal, White, Pre-Cooked`,
    main_type: `Dried Goods`,
    sub_type: `Canned Goods`,
  },
  {
    name: `Progresso Bread Crumbs, Plain`,
    main_type: `Dried Goods`,
    sub_type: `Other`,
  },
  {
    name: `Kikkoman Panko Japanese style bread crumbs`,
    main_type: `Dried Goods`,
    sub_type: `Other`,
  },
  {
    name: `Brads Organic Chia Seeds, Organic`,
    main_type: `Dried Goods`,
    sub_type: `Grains`,
  },
  {
    name: `Bob's Red Mill Whole Brown Flaxseed, Raw`,
    main_type: `Dried Goods`,
    sub_type: `Grains`,
  },
];
