/* eslint-disable no-undef */
module.exports = [
  { name: `Green Apple`, main_type: `produce`, sub_type: `fruit` },
  { name: `Banana`, main_type: `produce`, sub_type: `fruit` },
  { name: `Orange`, main_type: `produce`, sub_type: `fruit` },
  { name: `Strawberries`, main_type: `produce`, sub_type: `fruit` },
  { name: `Blueberries`, main_type: `produce`, sub_type: `fruit` },
  { name: `Green Grapes, Seedless`, main_type: `produce`, sub_type: `fruit` },
  { name: `Pineapple`, main_type: `produce`, sub_type: `fruit` },
  { name: `Mango`, main_type: `produce`, sub_type: `fruit` },
  { name: `Watermelon`, main_type: `produce`, sub_type: `fruit` },
  { name: `Cantaloupe`, main_type: `produce`, sub_type: `fruit` },
  { name: `Carrots`, main_type: `produce`, sub_type: `vegetable` },
  { name: `Broccoli`, main_type: `produce`, sub_type: `vegetable` },
  { name: `Cauliflower`, main_type: `produce`, sub_type: `vegetable` },
  { name: `Cucumber, Seedless`, main_type: `produce`, sub_type: `vegetable` },
  { name: `Spinach`, main_type: `produce`, sub_type: `vegetable` },
  { name: `Red Bell Pepper`, main_type: `produce`, sub_type: `vegetable` },
  { name: `Tomato, Vine`, main_type: `produce`, sub_type: `vegetable` },
  { name: `Zucchini`, main_type: `produce`, sub_type: `vegetable` },
  { name: `Onion, Spanish`, main_type: `produce`, sub_type: `vegetable` },
  { name: `Potato, Russet`, main_type: `produce`, sub_type: `vegetable` },
  { name: `Salmon, Farm-Raised`, main_type: `meat`, sub_type: `seafood` },
  { name: `Tuna, Bluefin`, main_type: `meat`, sub_type: `seafood` },
  {
    name: `Shrimp, Farm-Raised, Frozen`,
    main_type: `meat`,
    sub_type: `seafood`,
  },
  { name: `Scallop, U-10, Fresh`, main_type: `meat`, sub_type: `seafood` },
  { name: `Lobster, Live`, main_type: `meat`, sub_type: `seafood` },
  { name: `Chicken Breast`, main_type: `meat`, sub_type: `poultry` },
  { name: `Ground Turkey`, main_type: `meat`, sub_type: `poultry` },
  { name: `Duck Breast`, main_type: `meat`, sub_type: `poultry` },
  { name: `Cornish Game Hen`, main_type: `meat`, sub_type: `poultry` },
  { name: `Turkey Breast`, main_type: `meat`, sub_type: `poultry` },
  { name: `Pork Chop`, main_type: `meat`, sub_type: `pork` },
  { name: `Pork Tenderloin`, main_type: `meat`, sub_type: `pork` },
  { name: `Ground Pork`, main_type: `meat`, sub_type: `pork` },
  { name: `Baby Back Ribs`, main_type: `meat`, sub_type: `pork` },
  { name: `Bacon, Hickory`, main_type: `meat`, sub_type: `pork` },
  { name: `Ground Beef, 80/20`, main_type: `meat`, sub_type: `beef` },
  { name: `Steak, Sirloin`, main_type: `meat`, sub_type: `beef` },
  { name: `Steak, Ribeye`, main_type: `meat`, sub_type: `beef` },
  { name: `Beef Brisket`, main_type: `meat`, sub_type: `beef` },
  { name: `Beef Short Ribs`, main_type: `meat`, sub_type: `beef` },
  {
    name: `Organic Valley Milk, Organic, Whole`,
    main_type: `dairy-eggs`,
    sub_type: `milk`,
  },
  {
    name: `Land O Lakes Butter, Unsalted`,
    main_type: `dairy-eggs`,
    sub_type: `butter`,
  },
  { name: `Cheese, Manchego`, main_type: `dairy-eggs`, sub_type: `cheese` },
  {
    name: `Wallaby Organic No Sugar Added Greek Yogurt`,
    main_type: `dairy-eggs`,
    sub_type: `yogurt`,
  },
  {
    name: `Daisy Pure & Natural Sour Cream`,
    main_type: `dairy-eggs`,
    sub_type: `other`,
  },
  { name: `Large Eggs`, main_type: `dairy-eggs`, sub_type: `eggs` },
  { name: `Large Eggs, Free-Range`, main_type: `dairy-eggs`, sub_type: `eggs` },
  { name: `Quail Eggs, Free-Range`, main_type: `dairy-eggs`, sub_type: `eggs` },
  {
    name: `Liquid Death Mountain Water, 16.9 oz Cans`,
    main_type: `beverages`,
    sub_type: `water`,
  },
  {
    name: `VOSS Premium Still Bottled Water - 500ml`,
    main_type: `beverages`,
    sub_type: `water`,
  },
  {
    name: `Coca-Cola Cola, Original Taste`,
    main_type: `beverages`,
    sub_type: `soda`,
  },
  { name: `Simply Juice, Lemonade`, main_type: `beverages`, sub_type: `juice` },
  { name: `Lipton Black Tea`, main_type: `beverages`, sub_type: `tea` },
  {
    name: `Starbucks Coffee, 100% Arabica, Ground, Medium Roast, Breakfast Blend`,
    main_type: `beverages`,
    sub_type: `coffee`,
  },
  {
    name: `Red Bull Energy Drink, Sugar Free, 12 oz`,
    main_type: `beverages`,
    sub_type: `other`,
  },
  {
    name: `Gatorade Thirst Quencher, Lemon-Lime, 20 oz`,
    main_type: `beverages`,
    sub_type: `other`,
  },
  {
    name: `Vita Coco Coconut Water, The Original, 16.9 oz`,
    main_type: `beverages`,
    sub_type: `other`,
  },
  {
    name: `AriZona Iced Tea & Lemonade, Half and Half, Lite`,
    main_type: `beverages`,
    sub_type: `tea`,
  },
  {
    name: `Swiss Miss Hot Cocoa Mix, Marshmallow`,
    main_type: `beverages`,
    sub_type: `other`,
  },
  {
    name: `Health-Ade Kombucha, Pink Lady Apple`,
    main_type: `beverages`,
    sub_type: `other`,
  },
  {
    name: `Saratoga Spring Water, Carbonated`,
    main_type: `beverages`,
    sub_type: `water`,
  },
  {
    name: `Bragg Apple Cider Vinegar, Organic`,
    main_type: `dried-goods`,
    sub_type: `other`,
  },
  {
    name: `RiceSelect Jasmati, White`,
    main_type: `dried-goods`,
    sub_type: `grains`,
  },
  {
    name: `De Cecco Spaghetti, No. 12, Slow Dried`,
    main_type: `dried-goods`,
    sub_type: `grains`,
  },
  {
    name: `RiceSelect Tri-Color Quinoa 22 oz. Jar`,
    main_type: `dried-goods`,
    sub_type: `grains`,
  },
  { name: `Goya Lentils`, main_type: `dried-goods`, sub_type: `grains` },
  {
    name: `Goya Low Sodium Chick Peas`,
    main_type: `dried-goods`,
    sub_type: `canned-goods`,
  },
  {
    name: `Goya Premium Black Beans`,
    main_type: `dried-goods`,
    sub_type: `canned-goods`,
  },
  {
    name: `Near East Roasted Garlic & Olive Oil Couscous Mix`,
    main_type: `dried-goods`,
    sub_type: `grains`,
  },
  {
    name: `Quaker Oats, 100% Whole Grain, Quick 1-Minute`,
    main_type: `dried-goods`,
    sub_type: `other`,
  },
  {
    name: `Bear Naked Granola Cereal, Breakfast Snacks, Vanilla Almond`,
    main_type: `dried-goods`,
    sub_type: `other`,
  },
  {
    name: `P.A.N. Corn Meal, White, Pre-Cooked`,
    main_type: `dried-goods`,
    sub_type: `grains`,
  },
  {
    name: `Progresso Bread Crumbs, Plain`,
    main_type: `dried-goods`,
    sub_type: `other`,
  },
  {
    name: `Kikkoman Panko Japanese style bread crumbs`,
    main_type: `dried-goods`,
    sub_type: `other`,
  },
  {
    name: `Brads Organic Chia Seeds, Organic`,
    main_type: `dried-goods`,
    sub_type: `other`,
  },
  {
    name: `Bob's Red Mill Whole Brown Flaxseed, Raw`,
    main_type: `dried-goods`,
    sub_type: `other`,
  },
];
