module.exports = [
  { name: 'Green Apple', main_type: 'Produce', sub_type: 'Fruit' },
  { name: 'Bananas', main_type: 'Produce', sub_type: 'Fruit' },
  { name: 'Oranges', main_type: 'Produce', sub_type: 'Fruit' },
  { name: 'Strawberries', main_type: 'Produce', sub_type: 'Fruit' },
  { name: 'Blueberries', main_type: 'Produce', sub_type: 'Fruit' },
  { name: 'Grapes', main_type: 'Produce', sub_type: 'Fruit' },
  { name: 'Pineapple', main_type: 'Produce', sub_type: 'Fruit' },
  { name: 'Mango', main_type: 'Produce', sub_type: 'Fruit' },
  { name: 'Watermelon', main_type: 'Produce', sub_type: 'Fruit' },
  { name: 'Cantaloupe', main_type: 'Produce', sub_type: 'Fruit' },
  { name: 'Carrots', main_type: 'Produce', sub_type: 'Vegetable' },
  { name: 'Broccoli', main_type: 'Produce', sub_type: 'Vegetable' },
  { name: 'Cauliflower', main_type: 'Produce', sub_type: 'Vegetable' },
  { name: 'Cucumber', main_type: 'Produce', sub_type: 'Vegetable' },
  { name: 'Spinach', main_type: 'Produce', sub_type: 'Vegetable' },
  { name: 'Bell Peppers', main_type: 'Produce', sub_type: 'Vegetable' },
  { name: 'Tomatoes', main_type: 'Produce', sub_type: 'Vegetable' },
  { name: 'Zucchini', main_type: 'Produce', sub_type: 'Vegetable' },
  { name: 'Onion', main_type: 'Produce', sub_type: 'Vegetable' },
  { name: 'Potatoes', main_type: 'Produce', sub_type: 'Vegetable' },
  { name: 'Salmon', main_type: 'Meat', sub_type: 'Seafood' },
  { name: 'Tuna', main_type: 'Meat', sub_type: 'Seafood' },
  { name: 'Shrimp', main_type: 'Meat', sub_type: 'Seafood' },
  { name: 'Scallops', main_type: 'Meat', sub_type: 'Seafood' },
];
